apiVersion: v1
kind: Secret
metadata:
    name: minio-cnpg-conduit-backups
    namespace: conduit
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:BFEB5phVsou1WU1MvBAZhVilW1A=,iv:ev0p4GYSIJkY5kOrR3/qhgJ4luYmJAKAM/u6heNxyRY=,tag:Lxaot+n5Ds87E5RBeWwkfg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:abwLagRiJQFJ60iweyI/dcSaxLFZ4IPgdoCNf3HaCBohpRXa2Twjug==,iv:74I4EkmGpMWK/XA2aq2KwihNzNrLCMIFTTAr4yW+uN4=,tag:aZbnoPF0fYBu9pftPFyYog==,type:str]
sops:
    lastmodified: "2025-12-29T04:23:42Z"
    mac: ENC[AES256_GCM,data:iqqym37AhqvbJgwWX0gzoTEgRWevtG+xjygVQpRxr7iMGCYiOkIGKQYh6ugZKcokXS5Sl/dQgFGIArATBxgQQG67BW/AqFipGL2klAAkYhmFqXFDT8ITQfaRFq9V2PTzOiOT5fDRCrchOKgwMouxg4xsPHR9Z/36Ha5q81wpExY=,iv:4jkJQBsvce2ME7XkDkzPsHR6UW+m73rE7dLpCkbEK8U=,tag:yQXrmbWKOXaXFROWXoLQaA==,type:str]
    pgp:
        - created_at: "2025-12-29T04:23:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7e8MeuA+Z67ARAAp/JE1CLqrY5aOLFb/3KCLjTtDkyJhqRQ9Ufu9QWmIa1Z
            sHt03GIPLZAybCf5bC92VxRkBvm1VfCpeRom1G8p0hLC51OAgPynTolSTj6jtXm9
            feGHAFJdbuQqVxWYfrKTVzFQADdJYN6YBeqxCeJJFoDRuYhwqnbLB4BGm/1qgEl/
            ICa8Tspsizdg7G4cnIjViEp2W8w0n3MUokWICHQHARuXXs7DnLNdPzCk4pT84wMk
            jaQT5QPoTn0JJMGmdHWckBzcqNe0dhe9VNczswna7T1f1ta3edJeP0zvPCPNSXvC
            5ryF6ceYphrs2HhFH/xrZaPtaComTmqK+6p9GcVXq1KP4KImz1H8jgG8wB6Ebvsq
            ke+V6qBeM6miPOM3mBN5ADNXRMsr0r5aMftP3GwER7P2vBrL5qMTIN3TWyLIhh1T
            5vS1l5VZljCPfWQXSZjMY7Eb/RkWF1zrt/PjsPJWTOGT3S5iltEPCrrw5EFMd/YA
            QSp+2hMt/yNXjCw+bw3TD1FZb3Kj/lcwJRdFqVvqAHBINs82Y9z1yjwSQbLkwqrQ
            n0BgmuYqCPtMjMyH3rKD8U5dq2r2HrEhpE43iBKsn6+y/m/uoRDP2wCVEt7yjiSn
            AUv5j7KHfAuRnCrTwS30cJo3mIo0+TuaEOZkqQzqg7Zuw63pPFp7CpOmoBYHoNTS
            XAFX96TrHcoJFMgnf3YfL3Nx9RJoAvOdc3fe33D2SdJwxXQca/02ufyvYQskNy3e
            ekrnWF5NNKjybjOjkOeJEz7H9A376E+yDKS+xfwTlZMNzxmoc2Q6sOr/uT8B
            =6LOy
            -----END PGP MESSAGE-----
          fp: 82843FCE433398251FB23638568D8A5C3E0BA1C4
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
