---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-cnpg-conduit-backups
  namespace: conduit
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCQ5hwpOcXmiaMk4gzWMgVkTFh6Qn6Cioaua/3r0rPLlO9C1JO3z06jIMQNhtx888TOlPEZWi9wX9xebeCWKVqNzkK9nvXmTE0B4iK3oNqJkHYFSrinXy6U2Mim1FpC8VXMDEM7AJ//ooFSbi3gfmywAA+RWgGz8rrMdILp1vx2FyJNAtPH7Mqb8b2IgrbILRIPOEGOMFn9C0jWbMU27qq9Gfuw+V9YQ7gybndDK4ECuhMFLkcsCmVCZCWoe6cnaum3qVLZbpB27Njjw1EndyimsiLA+yqgiRqCyBtE7CJRgVxH1put0oO0pGD6f1xW0LSYO26Q9Nt7WUdQTGl7j09bRqBjDXKUkpHsqoR9zDJfck8RkKRQJh5akFSXshFv1vg0QfT54BdNVaCeVAUrBh0Gf2BpYCKUtFJ6SWv471YRT664lU1KGB2yr6iIrnnu7TnF+ehNvZm2MLRR6F9YiQp55YgYoCvRMxH1m91fzrKkYi93AbD1HitSE4CQ/ZkjR5toiCNo/7sJtHpBcG5Q4OEDMhgfAWf0KWD062306urjHPzZeT9tNDSX5fOocClon9guCU9b2crrBgmYsBz4r0cS722Lo7L1eF+lRH/ErarD/6V0XsCfPV1xjZOucTeJj9Nln2tAr4NnSU/vKr+VGjm/5XCQh1nM1iOu3jxsn+8DxgN3j2LG6Tl/QHz3xc9lNgIljQYBLj7Wg+OjYrWi+StRMtEMKQ==
    ACCESS_SECRET_KEY: AgBhi3LMELfUVWJgm1DzLGr2b1cEo9roT1l+XjJxvbi0gDT8IfxpQrDgm2M5md4ga8UQ/y3l06/rAfgxg21xxHdIDuzyQhHJ8xkm6Hj1DnVhSJp+GQ6Tcu7Q5E1crcZ9iCQBp6Kt38zGVK6vdBPXvK8xSMkEAa6c2YC/sFdz8VwNbrx4G1p96aM8fuadMhHzvs2rxWqHtadk+9VHneAJXubetJEx6NtI6oyfGml4VbwV9qnSocA5MJ4PAK4fMjTp9PLbSf3r9wqb27bbF8thfras1Gep8uiaj3yqtpAXWpjfZUxKZm7xtg5e0EnP35d9GohIyGIqpKasHzZLjlcg0GB20shpcqzs34C3ZKZaIKxr6ow/vxYFtSKCKgpP7ZluZ1FblY7qIKZ8EyhUlG/QG20GQAKnoe2AwKphPBBVYfp2LpnRapAG5fgOa7aknN1x/cIrRRwn57ymOQsdmaC88n05ZsRRm0hBG57H7Nuu3IIr0pb4z83jXJbb9Xv7GgjACu3v6zX1peOLYzwCA3UguK3cTAYSmMM9nY2TZjm9vNNAV+Y5JBjdljgIdNajqqJCC7hzay5ZuieT/b6do4q3INSFeUMPhIsvEDRbAc/4OnUQKs6ivKrZZDF7RuCRb+ehIetNMRskKtORxRu2dzKCRCIABRsoI/gfzEBNcZfUEqK3xyfFtdG+uSp0E67MsqeJzqs7ohobUqfXkZkhW313M4GLcvPWN11K3c8EcOjcwz9UDjiRPSETD1HP
  template:
    metadata:
      creationTimestamp: null
      name: minio-cnpg-conduit-backups
      namespace: conduit
    type: Opaque
