apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dashboard.fullname" . }}
  namespace: {{ template "dashboard.namespace" . }}
  labels: {{ include "dashboard.labels" . | nindent 4 }}
  {{- with $annotations := include "dashboard.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dashboard.fullname" . }}
  namespace: {{ template "dashboard.namespace" . }}
  labels: {{ include "dashboard.labels" . | nindent 4 }}
  {{- with $annotations := include "dashboard.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "cert-manager.io" ]
    resources: [ "certificates", "certificaterequests" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "cert-manager.io" ]
    resources: [ "certificates/status" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dashboard.fullname" . }}
  namespace: {{ template "dashboard.namespace" . }}
  labels: {{ include "dashboard.labels" . | nindent 4 }}
  {{- with $annotations := include "dashboard.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dashboard.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "dashboard.fullname" . }}
    namespace: {{ template "dashboard.namespace" . }}