apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dashboard.name" . }}
  namespace: {{ template "dashboard.namespace" . }}
  labels: {{ include "dashboard.labels" . | nindent 4 }}
  {{- with $annotations := include "dashboard.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "dashboard.name" . }}
  namespace: {{ template "dashboard.namespace" . }}
  labels: {{ include "dashboard.labels" . | nindent 4 }}
  {{- with $annotations := include "dashboard.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "dashboard.name" . }}
  namespace: {{ template "dashboard.namespace" . }}
  labels: {{ include "dashboard.labels" . | nindent 4 }}
  {{- with $annotations := include "dashboard.annotations" . }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "dashboard.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "dashboard.name" . }}
    namespace: {{ template "dashboard.namespace" . }}