services:
  dashboard-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: dashboard-site-dev
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5173:5173"
      - "127.0.0.1:2345:2345"
    environment:
      TZ: America/Los_Angeles
      GO_ENV: development
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/web/node_modules
    depends_on:
      - redis
      - postgres
    working_dir: /app
    command: ["/bin/sh", "/usr/local/bin/start-dev.sh"]
  redis:
    command: 'redis-server --save 60 1 --loglevel warning'
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    container_name: dashboard-redis-0
  postgres:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: conduit

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8090:8080
