apiVersion: v2
name: dashboard-site-chart
description: A Helm chart to deploy my dashboard
type: application
version: 0.1.4-rc3
home: https://github.com/Crowley723/dashboard-app
sources:
  - https://github.com/Crowley723/dashboard-app
maintainers:
  - name: Brynn Crowley
    email: littlehill723@gmail.com
    url: https://github.com/Crowley723
dependencies:
  - name: redis
    version: "20.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: cluster
    version: "~0.3.1"
    repository: "https://cloudnative-pg.github.io/charts"